### ISSUE TITLE
How can I use this with multiple browsers in one run ?

### ISSUE THREAD

**Issue by Paris778** [taktakpeops/jest-environment-browserstack#181]

**Comment by taktakpeops** [comment]
Hi,

It's explained in the README. The browser settings can be overridden at runtime in your beforeAll or beforeEach hook.

**Comment by Paris778** [comment]
Sorry, I wasn't able to make it work. Can you provide an example of how to make it work for both chrome and firefox in one run ? Thank you

**Comment by taktakpeops** [comment]
Hi,

You can find in the repositories a bunch of examples.

This file shows how to override the capabilities: https://github.com/taktakpeops/jest-environment-browserstack/blob/master/packages/core/src/__tests__/switch.spec.ts

**Comment by Paris778** [comment]
Thanks you're the best !!! And how can I automate testing for multiple browsers without copy pasting the same script with different browsers/browser versions ? (Sorry I'm trying to learn)

**Comment by taktakpeops** [comment]
As we are talking about JavaScript, you could keep your different browsers definition in a file that you import whenever it's needed.

If you have a gist or a repo with an example of what you want to achieve, feel free to share it here, I will review it and share feedback.

**Comment by Paris778** [comment]
Awesome !!! I'll work on it thanks !

**Comment by taktakpeops** [comment]
Closing the issue for now. Feel free to open a new one if you find something else.
