### ISSUE TITLE
Visual Testing is causing "Test environment browserstack cannot be found" when using node 12

### ISSUE THREAD

**Issue by tchia04** [taktakpeops/jest-environment-browserstack#28]
I followed the README.md and ran
cd examples/with-bt-local
yarn install
yarn test 
and I got the following error message
```

> 
`
$ yarn test
yarn run v1.19.0
$ npm-run-all -p -r start test:jest
$ PORT=8080 node scripts/start.js
$ jest --ci --runInBand
 PASS  src/App.test.js
 FAIL  src/__visual_testing__/App.test.js
  ● Test suite failed to run

    ● Validation Error:

      Test environment browserstack cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

      Configuration Documentation:
      https://jestjs.io/docs/configuration.html



        Test environment browserstack cannot be found. Make sure the testEnvironment configuration option points to an existing node module.

        Configuration Documentation:
        https://jestjs.io/docs/configuration.html
```

**Comment by tchia04** [comment]
I got around this issue by downgrade my node version from 12 to 10 using nvm. 

nvm use 10

**Comment by taktakpeops** [comment]
Hi,

Thank you for raising the issue.

You haven't built the project itself.

In the package.json, a relative path is used for the dependency. Therefore, it needs to be build locally first.

The README could specify it. I will add it.

**Comment by tchia04** [comment]
Thanks I figured that out after getting it to work with node10 and reading the package.json file.  It works for v12.13.1 for me now.

**Comment by taktakpeops** [comment]
Since it seems fixed, I close the issue.
