### ISSUE TITLE
BROWSERSTACK environment variables are not been used

### ISSUE THREAD

**Issue by tchia04** [taktakpeops/jest-environment-browserstack#29]
Even though I have the browserstack login credentials defined, it still says my login credential is invalid. 

env | grep -i browserstack
BROWSERSTACK_USERNAME=xxxx
BROWSERSTACK_ACCESS_KEY=yyyy

```
question Which command would you like to run?: test:visual
$ jest --testNamePattern=VisualTest --update-snapshot
 FAIL  src/App.e2e.test.js
  ● Test suite failed to run

    valid credentials for Browserstack are requierd

      at new BrowserstackEnvironment (node_modules/jest-environment-browserstack/lib/index.js:28:23)

 FAIL  src/__visual_testing__/App.test.js

```

**Comment by taktakpeops** [comment]
Hi,

As specified in the [README](https://github.com/taktakpeops/jest-environment-browserstack#credentials), `BROWSERSTACK_USER_NAME` and `BROWSERSTACK_ACCESS_KEY` should be exported in the environment.

**Comment by tchiaspko** [comment]
Can we use both? if you want to keep the BROWSERSTACK_USER_NAME consistent with the BROWSERSTACK_ACCESS_KEY

Many Browserstack documentations and packages are using BROWSERSTACK_USERNAME so it will make transition easier for people if BROWSERSTACK_USERNAME is supported also. 

If you search for "BROWSERSTACK_USERNAME" in the Browserstack github organization, it show 300 references
https://github.com/search?q=org%3Abrowserstack+BROWSERSTACK_USERNAME&type=Code

However if you search for "BROWSERSTACK_USER_NAME", it show 0 reference.
https://github.com/search?q=org%3Abrowserstack+BROWSERSTACK_USER_NAME
